In [1]:
import torch

data = [[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]
v = torch.tensor(data)
v

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [2]:
# 2 separate stacks of 3, 3x3 matrices
torch.zeros((2,3,3,3))

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [23]:
# Input vectors (4x3) (BxF)
x = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8],
                  [9, 9, 9]], dtype=torch.float32)

# Weight matrices (1x3)
W_Q = torch.tensor([[1, 1, 1]], dtype=torch.float32)
W_K = torch.tensor([[2, 2, 2]], dtype=torch.float32)
W_V = torch.tensor([[3, 3, 3]], dtype=torch.float32)

x = x.unsqueeze(2)

print(x)
print(x.shape)

# Compute Q, K, V (Bx3x1 @ Bx1x3 = Bx3x3)
Q = x @ W_Q
K = x @ W_K
V = x @ W_V

print("Q:", Q)
print("K:", K)
print("V:", V)

tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]],

        [[6.],
         [7.],
         [8.]],

        [[9.],
         [9.],
         [9.]]])
torch.Size([4, 3, 1])
Q: tensor([[[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.]],

        [[3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.]],

        [[6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.]],

        [[9., 9., 9.],
         [9., 9., 9.],
         [9., 9., 9.]]])
K: tensor([[[ 0.,  0.,  0.],
         [ 2.,  2.,  2.],
         [ 4.,  4.,  4.]],

        [[ 6.,  6.,  6.],
         [ 8.,  8.,  8.],
         [10., 10., 10.]],

        [[12., 12., 12.],
         [14., 14., 14.],
         [16., 16., 16.]],

        [[18., 18., 18.],
         [18., 18., 18.],
         [18., 18., 18.]]])
V: tensor([[[ 0.,  0.,  0.],
         [ 3.,  3.,  3.],
         [ 6.,  6.,  6.]],

        [[ 9.,  9.,  9.],
         [12., 12., 12.],
         [15., 15., 15.]],

        [[18., 18

In [25]:
import torch.nn.functional as F

# Compute attention scores (3x2 @ 2x3 = 3x3)
scores = Q @ K.transpose(1, 2) / torch.sqrt(torch.tensor(2.0))
attention_scores = F.softmax(scores, dim=-1)

print("Attention Scores:", attention_scores)
print(attention_scores.shape)

Attention Scores: tensor([[[3.3333e-01, 3.3333e-01, 3.3333e-01],
         [2.0352e-04, 1.4163e-02, 9.8563e-01],
         [4.2627e-08, 2.0644e-04, 9.9979e-01]],

        [[8.8037e-12, 2.9671e-06, 1.0000e+00],
         [1.8178e-15, 4.2636e-08, 1.0000e+00],
         [3.7536e-19, 6.1266e-10, 1.0000e+00]],

        [[7.7505e-23, 8.8038e-12, 1.0000e+00],
         [1.6004e-26, 1.2651e-13, 1.0000e+00],
         [3.3045e-30, 1.8178e-15, 1.0000e+00]],

        [[3.3333e-01, 3.3333e-01, 3.3333e-01],
         [3.3333e-01, 3.3333e-01, 3.3333e-01],
         [3.3333e-01, 3.3333e-01, 3.3333e-01]]])
torch.Size([4, 3, 3])
