In [1]:
import torch

data = [[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]
v = torch.tensor(data)
v

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [2]:
# 2 separate stacks of 3, 3x3 matrices
torch.zeros((2,3,3,3))

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [42]:
# Input vectors (1x3) (BxF)
x = torch.tensor([[0, 1, 2]], dtype=torch.float32)

# Weight matrices (1x3)
W_Q = torch.tensor([[1, 1, 1]], dtype=torch.float32)
W_K = torch.tensor([[2, 5, 2]], dtype=torch.float32)
W_V = torch.tensor([[1, 1, 1]], dtype=torch.float32)

x = x.unsqueeze(2)

print(x)
print(x.shape)

# Compute Q, K, V (Bx3x1 @ Bx1x3 = Bx3x3)
Q = x @ W_Q
K = x @ W_K
V = x @ W_V

print("Q:", Q)
print("K:", K)
print("V:", V)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])
Q: tensor([[[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.]]])
K: tensor([[[ 0.,  0.,  0.],
         [ 2.,  5.,  2.],
         [ 4., 10.,  4.]]])
V: tensor([[[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.]]])


In [45]:
import torch.nn.functional as F

# Compute attention scores (3x2 @ 2x3 = 3x3)
scores = Q @ K.transpose(1, 2) / torch.sqrt(torch.tensor(3.0))
attention_scores = F.softmax(scores, dim=-1)

print("Scores:", scores[0])
print("Attention Scores:", attention_scores[0])
print(attention_scores.shape)
v = attention_scores @ V.transpose(1, 2)
print(v)

Scores: tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.1962, 10.3923],
        [ 0.0000, 10.3923, 20.7846]])
Attention Scores: tensor([[3.3333e-01, 3.3333e-01, 3.3333e-01],
        [3.0498e-05, 5.5072e-03, 9.9446e-01],
        [9.4047e-10, 3.0667e-05, 9.9997e-01]])
torch.Size([1, 3, 3])
tensor([[[0., 1., 2.],
         [0., 1., 2.],
         [0., 1., 2.]]])
